# permissions for end users to edit customautoscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customautoscaling-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: autoscaler
    app.kubernetes.io/part-of: autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: customautoscaling-editor-role
rules:
- apiGroups:
  - buildpiper.opstreelabs.in
  resources:
  - customautoscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - buildpiper.opstreelabs.in
  resources:
  - customautoscalings/status
  verbs:
  - get
