
 
apiVersion: buildpiper.opstreelabs.in/v1
kind: CustomAutoScaling
metadata:
  name: my-autoscaler
  namespace: test2
spec:
  applicationRef:
    deploymentName: exporter-deployment
    deploymentPort: "8090"
    deploymentService: exporter-service
    
  scalingParamsMapping:
    cpu: 500m
    memory: 400Mi
  scalingQuery: |
    sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Namespace }}",pod_name="{{ .Name }}"}[1m])) by (pod_name) > 1
